server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Rutas de Astro SSG
    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    # Cache para assets estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|mp4)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}